variant seek-motion {
  from-start(u64),
  from-end(s64),
  forwards(s64),
  backwards(s64),
}

read-bytes: func(file-path: string, num-bytes: u64) -> expected<list<u8>, string>

seek-bytes: func(file-path: string, seek-motion: seek-motion) -> expected<u64, string>

write-bytes: func(file-path: string, buffer: list<u8>) -> expected<unit, string>

append-bytes: func(file-path: string, buffer: list<u8>) -> expected<unit, string>
