[package]
name = "wit-bindgen-demo"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ['cdylib']
test = false
doctest = false

[dependencies]
wit-bindgen-core = { path = '../bindgen-core' }
wit-bindgen-gen-guest-rust = { path = '../gen-guest-rust' }
wit-bindgen-gen-host-wasmtime-rust = { path = '../gen-host-wasmtime-rust' }
wit-bindgen-gen-host-wasmtime-py = { path = '../gen-host-wasmtime-py' }
wit-bindgen-gen-host-js = { path = '../gen-host-js' }
wit-bindgen-gen-guest-c = { path = '../gen-guest-c' }
wit-bindgen-gen-markdown = { path = '../gen-markdown' }
wit-bindgen-gen-guest-spidermonkey-js = { path = '../gen-guest-spidermonkey-js' }
wit-bindgen-guest-rust = { path = '../guest-rust' }
wasmprinter = "0.2.29"
